variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - build
  - deploy
build:
  stage: build
  image: node:13.12.0-alpine
  script:
    - yarn install
    - CI= yarn build
  artifacts:
    expire_in: 1 hour
    paths:
      - build

deploy_production:
    stage: deploy
    script:
        - echo "Deploying to server"
        - aws s3 cp --recursive ./build s3://www.ddd-tw.com
        - echo "Deployed"
    only:
        - master