image: node:14.11.0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build

build:
  stage: build
  before_script:
    - yarn
  script:
    - yarn build
  artifacts:
    expire_in: 1 hour
    paths:
      - public/
