image: node:14.11.0

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_REGION: $AWS_REGION
  S3_BUCKET_NAME: www.ddd-tw.com

stages:
  - build
  - deploy
build:
  stage: build
  variables:
    ALLOW_ROBOTS: "true"
  script:
    - yarn
    - CI= yarn build
  artifacts:
    expire_in: 1 hour
    paths:
      - public/

deploy_production:
  stage: deploy
  before_script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - eval $(aws ecr get-login --no-include-email --region $AWS_REGION | sed 's|https://||')
  script:
    - echo "Deploying to server"
    - aws s3 cp public/ s3://$S3_BUCKET_NAME/ --recursive --include "*"
    - echo "Deployed"
  only:
    - master
